---

- name: Setup git
  hosts: localhost
  tasks: 

  - name: Install git
    ansible.builtin.package:
      name: 
        - git 
        - git-crypt
      state: present
    become: true

  - name: Setup default git configuraiton ~/.gitconfig
    git_config:
      name: "{{ item.name }}"
      scope: global
      value: "{{ item.value }}"
    with_items:
      - {name: user.name,  value: IanJans }
      - {name: user.email, value: j.a.schonekerl@gmail.com }
      - {name: ui.color,   value: 'true' }
      - {name: core.editor,   value: vim }

